### ISSUE TITLE
ES6 for tape globbing util

### ISSUE THREAD

**Issue by emilbayes** [substack/tape#102]
Right now it's not possible to enable `--harmony` when using the tape globbing util.
I know that passing arguments to the shebang is not standardised and not possible across OS's. Is there some other way around this?

**Comment by saulshanabrook** [comment]
@Raynos is it possible to have this command as an npm script without referring directly to the path? Something like:

```json
  "scripts": {
    "test": "node --harmony tape 'tests/*.js'"
  },
```

But that doesn't work, because it cannot find module tape.

The reason is that I didn't install tape in that directory, because I am [running through docker](http://www.saulshanabrook.com/npm-docker-sharing-volumes/)...
