### ISSUE TITLE
Consider intercepting exceptions again and reporting them as failed tests

### ISSUE THREAD

**Issue by aghassemi** [substack/tape#106]
With https://github.com/substack/tape/pull/103 now any exceptions thrown when a test is running crashes the runner instead of just failing the test as it used to. I added a comment to https://github.com/substack/tape/pull/103 arguing exceptions thrown in test do not necessarily mean a bug in the test itself and can be result of bad changes in the underlying module it is trying to test and does not justify crashing and not running all other, possibly unaffected tests. 

I have run into this already where the API I am testing was changed in a bad way throwing exceptions with certain param values and instead of simply getting _2/50 tests failed_ kind of report, I am ending up with broken runner and not knowing what other tests were or were not affected by the underlying bad change.

**Comment by michaelrhodes** [comment]
I went ahead and [implemented the `tape-exceptions` suggestion](https://github.com/michaelrhodes/tape-catch). It took a few more lines of code, but it now passes all tape’s tests, so you should be able to just swap-and-go.

**Comment by Raynos** [comment]
@michaelrhodes noice.

Do you want to add it to the README of tape ?

**Comment by michaelrhodes** [comment]
@Raynos, sure, I’ll send a pull request.

**Comment by ehmicky** [comment]
I've created [a library](https://github.com/ehmicky/log-process-errors) that does just that. Instead of:

```bash
tape file.js
```

You just need to do:

```bash
tape -r log-process-errors/register/tape file.js
```

More information [here](https://github.com/ehmicky/log-process-errors/blob/master/docs/API.md#testing).

Bonus: this not only reports `uncaughtException` as failed tests, but also `unhandledRejection`, `rejectionHandled`, `multipleResolves` and `warning`.
