### ISSUE TITLE
Should true() mean === true, and not truthy? (And same for `false`)

### ISSUE THREAD

**Issue by pdubroy** [substack/tape#119]
I've recently been bitten by some tests I wrote that used `notOk` to check the return value of a function that was supposed to only return `true` or `false`. The tests were incorrectly passing because the function was returning undefined due to a control flow bug.

I would have thought that `true` and `false` would check strict equality, but I see that they don't. Would it make sense to change them to be that way? I can submit a pull request if you think it's worthwhile.

**Comment by rhys-vdw** [comment]
I'd like to request that this issue is reopened; it seems that it was closed without resolution.

A test case that permits different return values (ie. `true`, `10`, `'false'` etc. - all valid for `test.true`) seems like the minority case, if not an anti-pattern. Typically I would avoid these kinds of tests and insist on testing for a specific return value. A test case should be updated when the expected return value changes.

If `test.true()` only accepted the return value `true` then checking for a 'truthy' return value could still be achieved trivially (and unambiguously) like so:

```js
test.true(shouldBeTruthy == true)
```

If necessary you could restore the alias of `ok` with:

```js
test.truthy(shouldBeTruthy)
```

However, in my opinion, this incorrectly implies that this is the type of test one should be writing.

**Comment by ljharb** [comment]
To echo https://github.com/substack/tape/issues/119#issuecomment-62953919, `t.equal(expected, true)` is better than `t.ok`.

I agree that `t.true(x)` might be better aliased to `t.equal(x, true)`, but I think the explicitness of `t.equal` is preferred anyways, so I'm not sure I see the value of the breaking change.

**Comment by rhys-vdw** [comment]
> I think the explicitness of t.equal is preferred anyways, so I'm not sure I see the value of the breaking change

Agreed. It's surprising behaviour, but not a huge deal.

That said, the fact it's a breaking change has less significance for a test library like tap. Should be fairly easy for consuming code to correct (since tap enumerates a list of broken tests when you run it).
