### ISSUE TITLE
How to define new test methods?

### ISSUE THREAD

**Issue by mbostock** [substack/tape#154]
Say I want something like test.equal but tolerant of limited floating point precision. I might be tempted to say:

``` js
tape.Test.prototype.inDelta = function(actual, expected) {
  this._assert(expected - 1e-6 < actual && actual < expected + 1e-6, {
    message: 'should be in delta',
    operator: 'inDelta',
    actual: actual,
    expected: expected
  });
};
```

This mostly works, but fails to produce the correct “at” line when an error is reported due to how test._assert looks at the stack trace. This makes it hard to identify where the test is broken. For example:

```
  not ok 20 should be in delta
    ---
      operator: inDelta
      expected: 0.1
      actual:   0.010000000000000002
      at: Test.tape.Test.inDelta (/Users/mbostock/Development/d3-transition/test/ease-test.js:6:8)
    ...
```

Note that ease-test.js:6 is where the test._assert is called, not where test.inDelta is called.

I could do something like this instead:

``` js
function inDelta(actual, expected) {
  return expected - 1e-6 < actual && actual < expected + 1e-6;
}
```

And then `test.ok(inDelta(actual, expected))`. That fixes the “at” line, but now I can’t see the helpful “expected” and “actual” values:

```
  not ok 20 (unnamed assert)
    ---
      operator: ok
      expected: true
      actual:   false
      at: Test.<anonymous> (/Users/mbostock/Development/d3-transition/test/ease-test.js:60:8)
    ...
```

Apologies if this is answered somewhere already. I couldn’t find an answer.

**Comment by Raynos** [comment]
@mbostock 

The magic is here https://github.com/substack/tape/blob/master/lib/test.js#L231-L233

We scan the stack for the first line that does not come from `tape/lib/*.js`

I recommend you make modify tape to instead of checking for folder it should check for a "excludedFolders" list; this way you can mutate or sub class tape and add your folder to the blackList.

**Comment by substack** [comment]
I usually do this kind of thing instead, for what it's worth:

``` js
function approx (t, a, b, msg) {
  return t.ok(expected - 1e-6 < actual && actual < expected + 1e-6, msg);
}
```

and then you just pass in the `t` reference, instead of modifying the prototype globally.

**Comment by Raynos** [comment]
I do the same although more like:

"""
cluster.verifyGoodState(t, opts...)
"""

**Comment by MadLittleMods** [comment]
Using `t.ok` works for custom tests but it would be nice to be able to supply a custom fail message in order to give some more insight into the failure. Passing a custom `expect` and `actual` could also solve part of this issue.

**Comment by resotek** [comment]
I have a similar issue trying to define a custom t.contains test method: [How to write a custom assertion for testing node or javascript with tape, or check for substring rather than t.deepEquals()?](http://stackoverflow.com/questions/38599457/how-to-write-a-custom-assertion-for-testing-node-or-javascript-with-tape-or-che).

I have to choose between two unfortunate choices to test the text string generated by my main program:

1. use t.equals(), and then `actual:` shows `false` instead of the string my source code generated.
1. Specify the entire text I'm checking for, and my test script becomes almost as complex as my main code, and I have to continually edit the test string every time I make the slightest edit to the string generated by my code.

Has there been a decision regarding extending `t.ok` to pass a custom `actual`?

**Comment by ljharb** [comment]
Please open new issues if there's still changes you'd like to see.
