### ISSUE TITLE
Passing in a function to assert.throws doesn't seem to work

### ISSUE THREAD

**Issue by anthonypt87** [substack/tape#179]
assert.throws in tape doesn't seem to allow passing in a function as a second argument like https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message does.

**Comment by ljharb** [comment]
This seems like something worth adding - I'd like to see how `assert` itself differentiates between a constructor or a validation function though.

**Comment by tjconcept** [comment]
@ljharb that's here: https://github.com/nodejs/node/blob/3a2e75d9a5c31d20e429d505b82dd182e33f459a/lib/assert.js#L618

Basically, if it's a function, and it's got a `.prototype` property, and an `instanceof` check succeeds, then it's OK. Otherwise the "expected" is considered a validation function and called.

**Comment by ljharb** [comment]
This should be fixed in the nest v5 prerelease, by 547dc14cac4afad8d2e9dd91c5ffc617bc441eed
