### ISSUE TITLE
Recommended approach for running tape continuously as soon as watched files are edited?

### ISSUE THREAD

**Issue by gotofritz** [substack/tape#187]
Hi. What do you recommend for running tape continuously as soon as you change files? Runners like karma have this ability built in. Do we need to wrap tape in a gulp (or grunt, etc...) task? It's quite icky. It would be nice to have it builtin inside tape.
Thanks.

**Comment by scottcorgan** [comment]
https://github.com/Qard/onchange

**Comment by gotofritz** [comment]
Thanks. I assume there are no plans to have it built in within tape?

**Comment by scottcorgan** [comment]
I assume that it is out of the scope of the tape project. It all composes well together though.

**Comment by substack** [comment]
tape focused on outputting TAP to stdout so that other tools can focus on things like file watching. onchange is pretty good if you want something very simple. There are some tape runners like [prova](https://www.npmjs.com/package/prova) to give more integrated higher-level features like file-watching.

**Comment by rstacruz** [comment]
I've built a tool to handle this: https://github.com/rstacruz/tape-watch

It works differently from watchers like `onchange` in that it doesn't invoke your tape tests in a separate process. This may lead to some side effects in some edge cases of course, but for most cases it works pretty well. It's like `mocha --watch` for tape.

**Comment by Raynos** [comment]
Cool :)

**Comment by dmitriz** [comment]
@rstacruz
Is `tape-watch` still operational? 
Some tests are failing and the project looks like kind of abandoned, is it?

**Comment by gotofritz** [comment]
My rule of thumb: if you need to ask whether a project has been abandoned, it usually has.

**Comment by dmitriz** [comment]
@gotofritz
> My rule of thumb: if you need to ask whether a project has been abandoned, it usually has.

That is a sad rule and I've seen projects revived that way with former owner offering help or sometimes they don't make any changes because they consider the project completed.

The tape-watch [seems to be offering some better performance than other solutions](https://github.com/rstacruz/tape-watch#tape-watch):

> tape-watch is an auto-test runner for tape. It will re-run your tests when any of the files in your project changes. This is better than using watch or nodemon: it will reload your tests in the same Node.js process, saving you precious startup time.

And if I understand correctly, `onchange` works similar to watch or nodemon, while the other mentioned https://www.npmjs.com/package/prova had been last published 3 years ago.

That leaves the question, whether @rstacruz would still be interested to help fixing tape-watch.
