### ISSUE TITLE
More aliases to support multiple testing (BDD/TDD) styles

### ISSUE THREAD

**Issue by dacodekid** [substack/tape#205]
Would love to see few more alias functions.  For ex:
```javascript
const it = require('tape');

it('should make sense for BDD style', function (should) {
  should.throws(...) // acceptable
  should.doesNotThrow(...) // nope
  should.end();
});
```
My current workaround ...
```javascript
const it = require('tape');

it('should make sense for BDD style', function (should) {
  const myApp = should;
  should.throws(...) // acceptable
  myApp.doesNotThrow(...) // ok.....
});
```

Aliases like below would be much appreciated.
```javascript
(should).notThrow(...)
(should).beOk(...)
(should).notBeOk(...)
(expect).toFail(...)
(expect).toThrow(...)
```

**Comment by ljharb** [comment]
Why do you think you want BDD style?

**Comment by yoshuawuyts** [comment]
@dacodekid you're free to wrap `tape` to make it better suit your needs. I don't think this is something that should be part of the `tape` module, as it strongly deviates from the philosophy.

**Comment by dacodekid** [comment]
Though it's completely a style preference, there are places that ```it / should / expect``` makes much sense than ```t / assert```.  While lot other functions have their alias counter parts that goes well with other test suite styles, neither ```throws``` or ```doesNotThrow``` won't have such.

But thought such few aliases might help people from other suites  `feel home` (me one) to ``tape``.  If ```tape``` follows any spec to name after its functions, then I'm fine with it.

**Comment by yoshuawuyts** [comment]
how about:
```js
test('it should make sense for BDD style', function (t) {
  // test code goes here
})
```
I've honestly never understood the appeal of using `should`, I find it to be slightly confusing.

**Comment by Raynos** [comment]
:-1: no new things to the public interface...

**Comment by dacodekid** [comment]
Seems many other ```assert``` based test suites also following the same method names as ```tape``` does. So closing this ticket as it seems unnecessary. Thx all for ur input.

**Comment by mindplay-dk** [comment]
> I don't think this is something that should be part of the tape module, as it strongly deviates from the philosophy.

I strongly agree with this - it's what attracted me to Tape.

Since this discussion (?) it appears lots of aliases were added after all.

Why?

I thought your philosophy favorized consistent tests?

Why did you end up introducing a bunch of aliases?

It doesn't make the tests more readable, unless maybe you're reading them out loud and expecting source-code to read aloud like english - and are willing to trade off consistency in favor of that.

It doesn't make tests any easier to write. I have to parse and memorize a bunch of different names for the exact same thing. When auto-completing from `assert`, I have to pile through what is apprently a long list of assertions, but is in reality just different names for the same thing.

Why did you abandon your original philosophy?

Personally, I wish you'd return to your original philosophy in the next major release - deprecate all aliases and encourage everyone to update their tests for consistency.

**Comment by ljharb** [comment]
As far as i know, all the aliases we have are in `assert`; for which is this not true?

**Comment by Raynos** [comment]
I once tried to remove all the aliases. ( https://github.com/substack/tape/pull/124 ).

The breaking change is too expensive. You would need a new module.

**Comment by mindplay-dk** [comment]
> As far as i know, all the aliases we have are in `assert`

That's what I'm addressing, yes.

> I once tried to remove all the aliases

I'm suggesting we deprecate - I'm not suggesting the aliases be removed.

Not trying to make everyone's life a living hell, just trying not to *encourage* inconsistent tests :-)

**Comment by ljharb** [comment]
@mindplay-dk that sounds like a policy you'd want in your own codebase (and perhaps an `eslint-plugin-tape` with custom eslint rules would be useful!) but "deprecation" just isn't really going to add value imo if we never intend to remove them.

**Comment by mindplay-dk** [comment]
@ljharb well, the problem is not merely my codebase - the bigger problem is codebases using tape are going to be inconsistent, for no real reason, other than somebody's opinion about the best name to use; or worse, they're just going to randomly pick one. A linter plug-in would be a symptom of unnecessary complexity leading to more complexity.

The problem is making us choose in the first place - asking us to decide which alias to use, even though there is no benefit of choosing one over the other, and no benefit to the person reading the test and having to discern between them.

It's about as meaningful as making someone choose a color for every assertion. If I like blue better than green, I should get to choose, right? Why not? ;-)

> "deprecation" just isn't really going to add value imo if we never intend to remove them.

True, but then, I'd say, remove them - return to the philosophy of simplicity that made this test-framework attractive to begin with.

Just my two cents.
