### ISSUE TITLE
Asynchronous calls to `test` fail to run

### ISSUE THREAD

**Issue by KoryNunn** [substack/tape#234]
Test case here: https://github.com/KoryNunn/tape/blob/async-test-setup/test/async.js

It seems that if `test()` is called outside the initial tick, it wont run.

**Comment by jtlapp** [comment]
Yes, support for the `only` constraint requires this. `tape` queues up all of the tests in the current tick and executes them in a subsequent tick. It has to have seen all of the tests before it can execute any tests in order to know if an `only` test appeared among them. If you define a test in a later tick, it will follow the `tape` evaluation of the tests. It may still get executed, depending on timing and intervening tasks, but it may not, and it may not respect `only` either.

**Comment by KoryNunn** [comment]
Yeah I came to that conclusion eventually too, and now we use https://gist.github.com/KoryNunn/a7ddbfb069bbbb2a41b4 as a solution to the problem we had.
