### ISSUE TITLE
Only use function-bind when native isn't available

### ISSUE THREAD

**Issue by steelbrain** [substack/tape#253]
We should be ponyfilling instead of executing it all the time. It results in an error in runtimes which disallow the result of eval, like Chrome Apps and Atom. See https://github.com/AtomLinter/linter-stylelint/issues/90

The line in question is [`lib/index.js:8`](https://github.com/substack/tape/blob/87e4bec19bac80402011347f89b3647425d09c5e/lib/results.js#L8)

**Comment by steelbrain** [comment]
Resurrection of https://github.com/substack/tape/issues/199

**Comment by ljharb** [comment]
"ponyfill" is not a real word (and yes I'm aware that a few people try to pretend it is).

At any rate, while it'd be fine to do `Function.prototype.bind || require('function-bind')` it's not going to help anything wrt CSP and Chrome Apps. The solution remains (as pointed out in https://github.com/substack/tape/issues/199#issuecomment-147215863) to shim `function-bind` to `Function.prototype.bind` in an env in which you can rely on it being available.

**Comment by steelbrain** [comment]
> it's not going to help anything wrt CSP and Chrome Apps

Can you please explain why it won't help? I'm not sure about Chrome Apps as I have no experience working with them, I'm quite confident that in Atom you won't get a warning about a runtime feature being disallowed until it's executed and `Function.prototype.bind` is available in all Atom versions that I've tried it on, so I believe that a simple `Function.prototype.bind || require('function-bind')` will solve the problem

Please note that if we do not workaround this, packages will have to drop `tape` dependency and explore alternatives, like [`stylelint` did](https://github.com/AtomLinter/linter-stylelint/issues/90#issuecomment-183811474)

**Comment by ljharb** [comment]
My understanding is that Chrome Apps and CSP freak out when `Function` or `eval` occurs anywhere in the app - not just when it's executed. This means that the `||` will not avoid the CSP error.

If in fact is is the case that that is sufficient to bypass CSP, then I'd be happy to modify `function-bind` itself to export `Function.prototype.bind` when available - but I'm pretty confident it won't have any affect.

If you need to pursure another testing solution, that's fine, but when a single line in your package.json will allow browserify to replace `function-bind` with `Function.prototype.bind`, it seems like a simple fix on your end (because only on your end can you know for sure that `bind` is available)

**Comment by steelbrain** [comment]
I am not sure about the behavior in Chrome Apps but our use case is a package in Atom that is requiring this package, and I have personally verified that `Function.prototype.bind || new Function('')` does not produce this warning in Atom. Therefore if you do that, it will fix our use case and `stylelint` will be able to use this package again.

Our use case does not include browserify, so a manifest fix won't do it for us :)

**Comment by ljharb** [comment]
`function-bind` v1.1.0 is published - a fresh `npm install` should include the newest version. That should cover it if your theory is correct.

**Comment by steelbrain** [comment]
Beautiful, Thanks! :+1:

**Comment by steelbrain** [comment]
@ljharb I just confirmed it works, thanks again
