### ISSUE TITLE
Which is the preferred usage? plan(n) or end()?

### ISSUE THREAD

**Issue by TimBuckley** [substack/tape#289]
Assuming all else equal, is it preferred to use `end()` at the end of the test, or `plan(n)` at the beginning? Is one more performant?

It would seem that `t.end()` is much easier to use, as you don't have to maintain the number of assertions to check as with `t.plan(n)`. Are there situations where `plan` is better?

Using `t.end()`:
```
tape('test using end()', t => {
  t.equal(1, 1)
  t.equal(2, 2)
  t.end()
})
```
Using `t.plan(n)`:
```
tape('test using plan(n)', t => {
  t.plan(2)
  t.equal(1, 1)
  t.equal(2, 2)
})
```

**Comment by yoshuawuyts** [comment]
I'd recommend using `t.plan()` on every test. It provides stronger guarantees in async scenarios and makes sure comments are put on the right line in the output.

**Comment by ljharb** [comment]
I prefer often doing both. "plan" at the beginning to protect myself against hard-to-catch async test omissions, and "end" at the end to notify tape that i'm for sure done, to fail faster.

**Comment by Raynos** [comment]
I only ever use `end()` personally.

**Comment by snuggs** [comment]
@TimBuckley @Raynos  `.end()` where I can (which is quite often). `plan(n)` earlier on in the test example due to uncertanty.

In other news...Make some noise for `.end()` being lazier to type than `.plan(n)` IJS 🎉 🎆  

![image](https://cloud.githubusercontent.com/assets/38223/18101775/0711a8fc-6ebe-11e6-9c83-83942fd8ddc9.png)

**Comment by ljharb** [comment]
This appears answered thoroughly.
