### ISSUE TITLE
Using in the browser

### ISSUE THREAD

**Issue by treshugart** [substack/tape#333]
Tape seems to use some node built-ins but obviously that's not available to the browser. How does one go about this if they can't / don't want to use Browserify?

**Comment by substack** [comment]
Use browserify.

**Comment by treshugart** [comment]
Unfortunately Browserify isn't my thing. Too bad, because Tape is awesome! Thanks for the quick response.

**Comment by ljharb** [comment]
@treshugart the entire JS/npm ecosystem requires browserify, webpack, or something similar - modern JS development can't be done without them. Good luck!

**Comment by treshugart** [comment]
The responses here seem defensive, or condescending, but maybe text can be hard. I apologise; my question was genuine. I ask because the docs say "tap-producing test harness for node and browsers" but when you load the bundle in the browser it throws an error because it can't find Node's `fs` module.

I'm using Webpack, so maybe I can just add `{ target: 'node' }` or something like that? I can't test it at the moment and even if it works, it still leaves me wondering if there's any other caveats.

**Comment by ljharb** [comment]
@treshugart text is hard :-) I also apologize for coming off defensive and/or condescending.

Webpack should work just fine. As you can [see](https://github.com/substack/tape/search?utf8=✓&q=require%28%27fs%27%29), there's only one place where `fs` is required, and it's used [here](https://github.com/substack/tape/blob/c1b483c8c4d3f58677bacc106be13708dd73ef75/lib/default_stream.js#L21-L22) - as long as `fs` exists and `fs.writeSync` is falsy, it will work fine in the browser. As you may be able to see in the [browserify bundle](https://wzrd.in/debug-standalone/tape@latest), browserify shims `fs` by default as an empty module (id 1 in the output; grep for `{1:[` to find the start of the module) - which thus results in an empty object.

If you configure `webpack` to replace `fs` with an empty object, then anything that relies on browserify should work fine, including `tape`.

**Comment by ORESoftware** [comment]
Front-end development is crazytown, that's all I want to say after reading this thread.

**Comment by sergej-s** [comment]
In case some one will search the answer: add the next to your webpack config
```
node: {
  fs: 'empty'
},
```

**Comment by bennypowers** [comment]
> @treshugart the entire JS/npm ecosystem requires browserify, webpack, or something similar - modern JS development can't be done without them. Good luck!

That is simply not true. It may be a popular opinion, but its founded on FUD about the capabilities of the web platform.

I'd rather use tape for my browser testing than Mocha, but if I can't do that because the attitude of the tape developers is "everyone else is using complicated but strictly unnecessary tooling so you should to" then I'll have to forgo this awesome lib for now.

**Comment by ljharb** [comment]
@bennypowers it’s quite true, I’m afraid. You can certainly use tape via a simple build process, just like the majority of the JS packages out there. Its unfortunate if that means you choose not to use tape, but given that it’s the sole remaining test framework that works on older browsers (including mocha), you might be causing more problems for yourself than you think.

**Comment by bennypowers** [comment]
Maybe I missed something. Your claim was that the entire JS/npm ecosystem requires users to use a bundler. Yet, there are many libraries on that don't. In fact there are entire communities of developers who try as much as possible not to use any tooling at all asides from the browser (and I guess a keyboard)

So, it must not be true that the entire js/npm ecosystem requires a bundler.
So the argument that tape doesn't need to support those use cases because no one does doesn't obtain.

So say you don't want to directly support the browser - that's fine. I'm just advocating for a little truth in advertising here.

**Comment by ljharb** [comment]
There are certainly a minority of libraries that don’t; but the aggregate does.

We do directly support the browser - via a bundler. Native ESM would require using URLs, which are application-specific, and thus require tooling to customize. Using UMDs and dropping stuff in the global namespace is an archaic bad practice, and makes files larger for all users just to appease the “i don’t even own a tv” extremists who insist on avoiding tooling (yet who still use a minifier, i suspect).

**Comment by bennypowers** [comment]
> URLs, which are application-specific

unless they are relative URLs, so that's not a concern

> UMDs and dropping stuff in the global namespace is an archaic bad practice

Preach!

how about esm with relative urls?

**Comment by ljharb** [comment]
(Separately, this issue is about a browser build, not an ESM build - but that won’t come prior to node shipping it, and will come the instant node does)
