### ISSUE TITLE
Deeper `expected` and `actual` objects when comparing with `deepEqual`

### ISSUE THREAD

**Issue by markasoftware** [substack/tape#379]
When comparing many-leveled objects (for example, an array of objects containing arrays of objects containing arrays), at the innermost level it sometimes just says `[Object]` instead of fully expanding the tree, which isn't particularly useful for testing.

**Comment by ljharb** [comment]
Because circular references could exist, it either has to have cycle detection (pretty complex to do efficiently) or stop at a fixed depth.

object-inspect uses a [configurable fixed depth](https://github.com/substack/object-inspect#var-s--inspectobj-opts), which tape exposes as an undocumented test option ["objectPrintDepth"](https://github.com/substack/tape/blob/995ddb254ab5e6048b4d049b902601b597ff24e0/lib/results.js#L145-146) - a PR to document it would be appreciated.

(Separately, deeply nested objects are a code smell, so I'd recommend avoiding that structure)

**Comment by markasoftware** [comment]
Thanks. BTW, `objectPrintDepth` does seem to be documented in the readme, I just missed it while skimming over.
