### ISSUE TITLE
Negative zero, positive zero, deepEqual behaviour changed between 4.11.0 and 4.13.2

### ISSUE THREAD

**Issue by AnyhowStep** [substack/tape#499]
This passed in 4.11.0,
```js
t.deepEqual(0, -0)
```

It broke in 4.13.2

https://xkcd.com/1172/

I've downgraded to 4.11.0 for now

**Comment by ljharb** [comment]
This suggests that you have an invalid dependency graph - tape v4 requires `deep-equal` v1, and that behavior changed in `deep-equal` v2. What does `npm ls` say?

**Comment by ljharb** [comment]
According to runkit, this test passes in 4.11 but fails in 4.12. Checking https://github.com/substack/tape/compare/v4.11.0...v4.12.0 points me to 6e94800578340a8cab9e0f357c380ab78f09b2cd, which updates deep-equal from v1.0 to v1.1. This change leads to https://github.com/inspect-js/node-deep-equal/compare/v1.0.1...v1.1.0

in which yes, deep-equal fixed a bug related to positive and negative zero (https://github.com/inspect-js/node-deep-equal/commit/28fde4a411073e3131d3637248f8c25aac9329f2 / https://github.com/inspect-js/node-deep-equal/pull/20).

Since `deepEqual` is strict by default, you want `t.deepLooseEqual(0, -0)`.

**Comment by ljharb** [comment]
Also, try testing out `tape@next` for the v5 prerelease - that's probably more worth your time updating your tests to.

**Comment by AnyhowStep** [comment]
Thanks for looking into this! I'll give it a go
