### ISSUE TITLE
before/beforeEach/after/afterEach

### ISSUE THREAD

**Issue by thom4parisot** [substack/tape#59]
Hello :-)

I'm considering using `tape` for a project requiring IE8 testing, in order to replace `chai`/`mocha`.

Is there any way to achieve doing `before`/`beforeEach`/`after`/`afterEach` to setup fixtures and stubs before running assertions?

Thanks very much :-)

**Comment by knownasilya** [comment]
For others that are interested, there is a package called [redtape](https://www.npmjs.com/package/redtape) that extends `tape` to give you `beforeEach` and `afterEach` functionality.

**Comment by braddunbar** [comment]
> For before()/after() you can just use ordinary tests to do setup and teardown:

So simple… :heart:

**Comment by sinkingshriek** [comment]
@Raynos I just wanna say that, that is some clever piece of code there. My mind was figuratively blown when I finally understood what was going on. :clap:

**Comment by tomekwi** [comment]
@oncletom @Raynos @sinkingshriek you can also [listen to the `end` event](https://github.com/studio-b12/tape-css/blob/0c9285b89b08ecf38d118ecae1beedf8bbe6e875/module/index.js#L57-L81) on `assert`. Benefit: it also works with `assert.plan`.

**Comment by kuraga** [comment]
Any ideas about merging this functionality? From [tapes](https://github.com/scottcorgan/tapes), for instance...

**Comment by alathon** [comment]
Also ran into this. Thanks for the excellent idea @Raynos. I'm still not 100% satisfied with this, as it prevents accessing the Test object to set eg. tape.onFinished(), so that has to be done before you ever call beforeEach (afaik?), f.ex.

I ended up re-implementing it slightly, so that the beforeEach/afterEach methods can take either a function, or an array of functions, as follows:

```javascript
exports.beforeEach = (_test, handlers) => {
  if (typeof handlers === 'function') return _beforeEach(_test, handlers)

  return handlers.reduce((prev, cur, curIdx, arr) => {
    if (curIdx === 0) return prev
    return _beforeEach(prev, cur)
  }, _beforeEach(_test, handlers[0]))
}

exports.afterEach = (_test, handlers) => {
  if (typeof handlers === 'function') return _afterEach(_test, handlers)

  return handlers.reduce((prev, cur, curIdx, arr) => {
    if (curIdx === 0) return prev
    return _afterEach(prev, cur)
  }, _afterEach(_test, handlers[0]))
}

const _beforeEach = (_test, handler) => {
  return function tapish (name, listener) {
    _test(name, function (assert) {
      let _end = assert.end

      assert.end = function () {
        assert.end = _end
        listener(assert)
      }

      handler(assert)
    })
  }
}

const _afterEach = (_test, handler) => {
  return function tapish (name, listener) {
    _test(name, function (assert) {
      let _end = assert.end

      assert.end = function () {
        assert.end = _end
        handler(assert)
      }

      listener(assert)
    })
  }
}
```

Use is f.ex:

```javascript
import tapeLib from 'tape'
import { beforeEach, someMethodA, someMethodB, someMethodC } from './helpers/hooks'

let tape = beforeEach(tapeLib, dropTables) // dropTables will run before each test.
tape = beforeEach(tape, [someMethodB, someMethodC]) // dropTables -> someMethodB -> someMethodC will run before each test
```

This allows you to separate the functionality into smaller methods that each do a certain thing, such as resetting your DB, or whatever else you need to do before tests.

**Comment by Raynos** [comment]
@alathon I've since written `tape-cluster` ( https://github.com/Raynos/tape-cluster ).

This allows you to build a generic class for your test suite, useful if your testing an app and want to setup & teardown the app before every test.

Bonus feature is that `MyTest.test.only();` and `MyTest.test.skip()` work. 
Bonus feature, you can pass options into your test class so that you can different configurations before every test.

**Comment by ChopperLee2011** [comment]
@substack  your code is clear, but not fit with `only` case, if one test case is describe with test.only, then all the setup and teardown are skiped

**Comment by JasinYip** [comment]
The above solutions looks can only be used for the whole testing. It couldn't set `beforeEach`/`afterEach` or `before`/`after` for every single file because these solutions would modify the `test` object which is a single instance.

**Comment by JasinYip** [comment]
Set alias from `test` function for implementing `before` and `after` might work around for calling order, but it would make side effects that we would see it on the result list. That might make the report looks not the same with the test case writers' expection.
