### ISSUE TITLE
print the file name tape is running in for debuggability

### ISSUE THREAD

**Issue by Raynos** [substack/tape#70]
When a test suite grows to multiple files it's hard to tell which file a given failed assert belongs to.

One thing that can be done is

``` js
test("testing {{file}}.js", function (assert) {
  assert.end()
})
```

This approach works today but is tedious.

A different approach is for the `lib/test.js` constructor to create a `new Error()` and read `new Error().stack` then find the caller file and store it in the test object.

Then the `lib/results.js` reporter we can see the fileName on every emitted result. When the fileName changes from the previous one we know that we are running a test block in a new file so we can just print that file as a comment in some form.

This way we have comments for files and comments for the name in the test block.

Then reporters downstream like `faucet` and `tap-spec` can do pretty things with them. 

Like `faucet --file` can collapse all the asserts in a file rather then all the asserts in a test block (for super terse ness).

I can make a PR for this.

**Comment by grit96** [comment]
:+1: This is much needed. I couldn't get `faucet --file` working so I'm using `tap-spec` instead.

**Comment by chesles** [comment]
I couldn't find the PR you mentioned, but it looks like this is implemented. It doesn't play very nicely with browserify though. Depending on the browser , I get either no filename at all or something marginally helpful like "localhost:8080/bundle.js:30291"

A little bit of searching turned up a few packages for applying a source map to stack traces. It might be cool to use something like this when running in a browser so that failure messages actually show where the failure is coming from.

**Comment by ljharb** [comment]
Seems like #330 may have done it?

Please file new issues if there's still something needed.
