### ISSUE TITLE
Test parallelization

### ISSUE THREAD

**Issue by ericedem** [substack/tape#78]
It seems like it would be possible to introduce some level of parallelization or batching to this framework. Since all tap output is generated by t.xxx(), it would be possible to save the output per test and then output test output at the end of a test run.

This would, of course, leave the user open to race conditions in their code, but it is useful for doing simple things like running selenium tests which are inherently async, and time consuming purely due to net traffic.

**Comment by Marak** [comment]
Has anyone else built any wrappers for running `tape` or `tap` tests in parallel with node?

I'm trying to use `prove` but haven't quite gotten it to work.

Sequential tests are essential and desired most of the time. In some cases, parallel tests can significantly reduce the amount of time spent running the tests. 

The reason I'm asking is because I have a headless integration test suite that requires some time to run. I now have to run these same tests in multiple browser environments at once. Running every browser configuration in sequence will just take too much time.

**Comment by markstos** [comment]
@Marak did you find the documentation for the `--rules` option to prove, which allows you to specify which tests to run in sequence vs parallel?

http://perldoc.perl.org/prove.html#--rules

I wrote some of those docs, but had some trouble getting exactly the results that I wanted as well.   

Trivia: prove has been able to run parallel tests with exceptions to run some sequentially since 2008. I believe the code was originally added to support the needs of the test suite of perl itself.

**Comment by trentm** [comment]
prove working well for me like this:

```
prove -j9 -e ./node_modules/.bin/tape \
		test/unit/*.test.js test/integration/*.test.js
```

Lovely.

**Comment by Marak** [comment]
@markstos - I'm coming back around to this soon and still require a solution. Whatever I end up doing I will post here.

I don't like the idea of having to add a strange new binary to our stack, but `prove` does seem well established and tested. I began to search the documentation and rules, but I couldn't find anything about specifying a maximum concurrency limit.

For example, we'll need to run a lot of tests with saucelabs in parallel. The sauce labs API has a hard concurrency limit for API requests, so our parrelization needs to have a limit on the amount of concurrently running tests. Not sure if `prove` is able to do that?

**Comment by markstos** [comment]
@Marak The `-j` option limits the number of parallel jobs run at the same time. It's up to you to control any /concurrency/ of tests that may happen within a particular job.   Since I don't find the words "parallel" or "concurrent" in the `tape` README, I presume it usually runs tests serially, and thus there is no additional concurrency to worry about. 

 `prove` is a great tool that happens to be in Perl and is well worth considering despite coming from a different language cultural. The "Test Anything Protocol" that `tape` is based on [came from Perl culture](https://en.wikipedia.org/wiki/Test_Anything_Protocol#History).  Using `prove` as a *TAP consumer*  for a *TAP producer* like `tape` is exactly what it is designed to do.
